// Generated by gencpp from file brain_msgs/AccessoryCmd.msg
// DO NOT EDIT!


#ifndef BRAIN_MSGS_MESSAGE_ACCESSORYCMD_H
#define BRAIN_MSGS_MESSAGE_ACCESSORYCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <brain_msgs/TurnSignal.h>

namespace brain_msgs
{
template <class ContainerAllocator>
struct AccessoryCmd_
{
  typedef AccessoryCmd_<ContainerAllocator> Type;

  AccessoryCmd_()
    : header()
    , signal()
    , door_lock(0)
    , door_open_right(0)
    , door_open_left(0)  {
    }
  AccessoryCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , signal(_alloc)
    , door_lock(0)
    , door_open_right(0)
    , door_open_left(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::brain_msgs::TurnSignal_<ContainerAllocator>  _signal_type;
  _signal_type signal;

   typedef uint8_t _door_lock_type;
  _door_lock_type door_lock;

   typedef uint8_t _door_open_right_type;
  _door_open_right_type door_open_right;

   typedef uint8_t _door_open_left_type;
  _door_open_left_type door_open_left;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(unlock)
  #undef unlock
#endif
#if defined(_WIN32) && defined(locked)
  #undef locked
#endif
#if defined(_WIN32) && defined(inactive)
  #undef inactive
#endif
#if defined(_WIN32) && defined(closed)
  #undef closed
#endif
#if defined(_WIN32) && defined(open)
  #undef open
#endif

  enum {
    unlock = 0u,
    locked = 1u,
    inactive = 0u,
    closed = 1u,
    open = 2u,
  };


  typedef boost::shared_ptr< ::brain_msgs::AccessoryCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brain_msgs::AccessoryCmd_<ContainerAllocator> const> ConstPtr;

}; // struct AccessoryCmd_

typedef ::brain_msgs::AccessoryCmd_<std::allocator<void> > AccessoryCmd;

typedef boost::shared_ptr< ::brain_msgs::AccessoryCmd > AccessoryCmdPtr;
typedef boost::shared_ptr< ::brain_msgs::AccessoryCmd const> AccessoryCmdConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brain_msgs::AccessoryCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brain_msgs::AccessoryCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brain_msgs::AccessoryCmd_<ContainerAllocator1> & lhs, const ::brain_msgs::AccessoryCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.signal == rhs.signal &&
    lhs.door_lock == rhs.door_lock &&
    lhs.door_open_right == rhs.door_open_right &&
    lhs.door_open_left == rhs.door_open_left;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brain_msgs::AccessoryCmd_<ContainerAllocator1> & lhs, const ::brain_msgs::AccessoryCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brain_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::AccessoryCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::AccessoryCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::AccessoryCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::AccessoryCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::AccessoryCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::AccessoryCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brain_msgs::AccessoryCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31dac8065b2447bde608272a85a25335";
  }

  static const char* value(const ::brain_msgs::AccessoryCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31dac8065b2447bdULL;
  static const uint64_t static_value2 = 0xe608272a85a25335ULL;
};

template<class ContainerAllocator>
struct DataType< ::brain_msgs::AccessoryCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brain_msgs/AccessoryCmd";
  }

  static const char* value(const ::brain_msgs::AccessoryCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brain_msgs::AccessoryCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header        header \n"
"\n"
"brain_msgs/TurnSignal  signal\n"
"\n"
"uint8 door_lock\n"
"uint8 unlock=0\n"
"uint8 locked=1\n"
"\n"
"uint8 door_open_right\n"
"uint8 door_open_left\n"
"uint8 inactive=0\n"
"uint8 closed=1\n"
"uint8 open=2\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: brain_msgs/TurnSignal\n"
"uint8 signal\n"
"uint8 off=0\n"
"uint8 left=1\n"
"uint8 right=2\n"
"uint8 hazard=3\n"
;
  }

  static const char* value(const ::brain_msgs::AccessoryCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brain_msgs::AccessoryCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.signal);
      stream.next(m.door_lock);
      stream.next(m.door_open_right);
      stream.next(m.door_open_left);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AccessoryCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brain_msgs::AccessoryCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brain_msgs::AccessoryCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "signal: ";
    s << std::endl;
    Printer< ::brain_msgs::TurnSignal_<ContainerAllocator> >::stream(s, indent + "  ", v.signal);
    s << indent << "door_lock: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.door_lock);
    s << indent << "door_open_right: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.door_open_right);
    s << indent << "door_open_left: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.door_open_left);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRAIN_MSGS_MESSAGE_ACCESSORYCMD_H
