// Generated by gencpp from file brain_msgs/AutonomousMode.msg
// DO NOT EDIT!


#ifndef BRAIN_MSGS_MESSAGE_AUTONOMOUSMODE_H
#define BRAIN_MSGS_MESSAGE_AUTONOMOUSMODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace brain_msgs
{
template <class ContainerAllocator>
struct AutonomousMode_
{
  typedef AutonomousMode_<ContainerAllocator> Type;

  AutonomousMode_()
    : header()
    , operation_mode(0)
    , autonomous_mode(0)  {
    }
  AutonomousMode_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , operation_mode(0)
    , autonomous_mode(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _operation_mode_type;
  _operation_mode_type operation_mode;

   typedef uint8_t _autonomous_mode_type;
  _autonomous_mode_type autonomous_mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(manual)
  #undef manual
#endif
#if defined(_WIN32) && defined(autonomous)
  #undef autonomous
#endif
#if defined(_WIN32) && defined(ready)
  #undef ready
#endif
#if defined(_WIN32) && defined(run)
  #undef run
#endif
#if defined(_WIN32) && defined(pause)
  #undef pause
#endif

  enum {
    manual = 0u,
    autonomous = 1u,
    ready = 0u,
    run = 1u,
    pause = 2u,
  };


  typedef boost::shared_ptr< ::brain_msgs::AutonomousMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brain_msgs::AutonomousMode_<ContainerAllocator> const> ConstPtr;

}; // struct AutonomousMode_

typedef ::brain_msgs::AutonomousMode_<std::allocator<void> > AutonomousMode;

typedef boost::shared_ptr< ::brain_msgs::AutonomousMode > AutonomousModePtr;
typedef boost::shared_ptr< ::brain_msgs::AutonomousMode const> AutonomousModeConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brain_msgs::AutonomousMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brain_msgs::AutonomousMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brain_msgs::AutonomousMode_<ContainerAllocator1> & lhs, const ::brain_msgs::AutonomousMode_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.operation_mode == rhs.operation_mode &&
    lhs.autonomous_mode == rhs.autonomous_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brain_msgs::AutonomousMode_<ContainerAllocator1> & lhs, const ::brain_msgs::AutonomousMode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brain_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::AutonomousMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::AutonomousMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::AutonomousMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::AutonomousMode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::AutonomousMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::AutonomousMode_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brain_msgs::AutonomousMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83fc74ab7fb7f6ab17301b0db27bca14";
  }

  static const char* value(const ::brain_msgs::AutonomousMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83fc74ab7fb7f6abULL;
  static const uint64_t static_value2 = 0x17301b0db27bca14ULL;
};

template<class ContainerAllocator>
struct DataType< ::brain_msgs::AutonomousMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brain_msgs/AutonomousMode";
  }

  static const char* value(const ::brain_msgs::AutonomousMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brain_msgs::AutonomousMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header \n"
"\n"
"uint8           operation_mode\n"
"uint8           manual=0\n"
"uint8           autonomous=1\n"
"\n"
"uint8           autonomous_mode\n"
"uint8           ready=0\n"
"uint8           run=1\n"
"uint8           pause=2\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::brain_msgs::AutonomousMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brain_msgs::AutonomousMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.operation_mode);
      stream.next(m.autonomous_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AutonomousMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brain_msgs::AutonomousMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brain_msgs::AutonomousMode_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "operation_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.operation_mode);
    s << indent << "autonomous_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.autonomous_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRAIN_MSGS_MESSAGE_AUTONOMOUSMODE_H
