// Generated by gencpp from file brain_msgs/Feature.msg
// DO NOT EDIT!


#ifndef BRAIN_MSGS_MESSAGE_FEATURE_H
#define BRAIN_MSGS_MESSAGE_FEATURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace brain_msgs
{
template <class ContainerAllocator>
struct Feature_
{
  typedef Feature_<ContainerAllocator> Type;

  Feature_()
    : header()
    , features()
    , type(0)
    , dimmension()  {
    }
  Feature_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , features(_alloc)
    , type(0)
    , dimmension(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _features_type;
  _features_type features;

   typedef uint8_t _type_type;
  _type_type type;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _dimmension_type;
  _dimmension_type dimmension;





  typedef boost::shared_ptr< ::brain_msgs::Feature_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brain_msgs::Feature_<ContainerAllocator> const> ConstPtr;

}; // struct Feature_

typedef ::brain_msgs::Feature_<std::allocator<void> > Feature;

typedef boost::shared_ptr< ::brain_msgs::Feature > FeaturePtr;
typedef boost::shared_ptr< ::brain_msgs::Feature const> FeatureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brain_msgs::Feature_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brain_msgs::Feature_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brain_msgs::Feature_<ContainerAllocator1> & lhs, const ::brain_msgs::Feature_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.features == rhs.features &&
    lhs.type == rhs.type &&
    lhs.dimmension == rhs.dimmension;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brain_msgs::Feature_<ContainerAllocator1> & lhs, const ::brain_msgs::Feature_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brain_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::Feature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::Feature_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::Feature_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::Feature_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::Feature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::Feature_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brain_msgs::Feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ab740099555ce0ec83d33024a0cceb7";
  }

  static const char* value(const ::brain_msgs::Feature_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ab740099555ce0eULL;
  static const uint64_t static_value2 = 0xc83d33024a0cceb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::brain_msgs::Feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brain_msgs/Feature";
  }

  static const char* value(const ::brain_msgs::Feature_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brain_msgs::Feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float64[] features\n"
"uint8 type\n"
"uint8[] dimmension\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::brain_msgs::Feature_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brain_msgs::Feature_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.features);
      stream.next(m.type);
      stream.next(m.dimmension);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Feature_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brain_msgs::Feature_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brain_msgs::Feature_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "features[]" << std::endl;
    for (size_t i = 0; i < v.features.size(); ++i)
    {
      s << indent << "  features[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.features[i]);
    }
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "dimmension[]" << std::endl;
    for (size_t i = 0; i < v.dimmension.size(); ++i)
    {
      s << indent << "  dimmension[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.dimmension[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRAIN_MSGS_MESSAGE_FEATURE_H
