// Generated by gencpp from file brain_msgs/Gear.msg
// DO NOT EDIT!


#ifndef BRAIN_MSGS_MESSAGE_GEAR_H
#define BRAIN_MSGS_MESSAGE_GEAR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace brain_msgs
{
template <class ContainerAllocator>
struct Gear_
{
  typedef Gear_<ContainerAllocator> Type;

  Gear_()
    : gear(0)  {
    }
  Gear_(const ContainerAllocator& _alloc)
    : gear(0)  {
  (void)_alloc;
    }



   typedef uint8_t _gear_type;
  _gear_type gear;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(inactive)
  #undef inactive
#endif
#if defined(_WIN32) && defined(gear_p)
  #undef gear_p
#endif
#if defined(_WIN32) && defined(gear_r)
  #undef gear_r
#endif
#if defined(_WIN32) && defined(gear_n)
  #undef gear_n
#endif
#if defined(_WIN32) && defined(gear_d)
  #undef gear_d
#endif

  enum {
    inactive = 0u,
    gear_p = 1u,
    gear_r = 2u,
    gear_n = 3u,
    gear_d = 4u,
  };


  typedef boost::shared_ptr< ::brain_msgs::Gear_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brain_msgs::Gear_<ContainerAllocator> const> ConstPtr;

}; // struct Gear_

typedef ::brain_msgs::Gear_<std::allocator<void> > Gear;

typedef boost::shared_ptr< ::brain_msgs::Gear > GearPtr;
typedef boost::shared_ptr< ::brain_msgs::Gear const> GearConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brain_msgs::Gear_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brain_msgs::Gear_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brain_msgs::Gear_<ContainerAllocator1> & lhs, const ::brain_msgs::Gear_<ContainerAllocator2> & rhs)
{
  return lhs.gear == rhs.gear;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brain_msgs::Gear_<ContainerAllocator1> & lhs, const ::brain_msgs::Gear_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brain_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::Gear_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::Gear_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::Gear_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::Gear_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::Gear_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::Gear_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brain_msgs::Gear_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01ce3f15169ff76eef9dff543b45f0cc";
  }

  static const char* value(const ::brain_msgs::Gear_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01ce3f15169ff76eULL;
  static const uint64_t static_value2 = 0xef9dff543b45f0ccULL;
};

template<class ContainerAllocator>
struct DataType< ::brain_msgs::Gear_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brain_msgs/Gear";
  }

  static const char* value(const ::brain_msgs::Gear_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brain_msgs::Gear_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 gear\n"
"uint8 inactive=0\n"
"uint8 gear_p=1\n"
"uint8 gear_r=2\n"
"uint8 gear_n=3\n"
"uint8 gear_d=4\n"
;
  }

  static const char* value(const ::brain_msgs::Gear_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brain_msgs::Gear_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gear_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brain_msgs::Gear_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brain_msgs::Gear_<ContainerAllocator>& v)
  {
    s << indent << "gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRAIN_MSGS_MESSAGE_GEAR_H
