// Generated by gencpp from file brain_msgs/LanePath.msg
// DO NOT EDIT!


#ifndef BRAIN_MSGS_MESSAGE_LANEPATH_H
#define BRAIN_MSGS_MESSAGE_LANEPATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <brain_msgs/Relation.h>

namespace brain_msgs
{
template <class ContainerAllocator>
struct LanePath_
{
  typedef LanePath_<ContainerAllocator> Type;

  LanePath_()
    : path()  {
    }
  LanePath_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::brain_msgs::Relation_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::brain_msgs::Relation_<ContainerAllocator> >> _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::brain_msgs::LanePath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brain_msgs::LanePath_<ContainerAllocator> const> ConstPtr;

}; // struct LanePath_

typedef ::brain_msgs::LanePath_<std::allocator<void> > LanePath;

typedef boost::shared_ptr< ::brain_msgs::LanePath > LanePathPtr;
typedef boost::shared_ptr< ::brain_msgs::LanePath const> LanePathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brain_msgs::LanePath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brain_msgs::LanePath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brain_msgs::LanePath_<ContainerAllocator1> & lhs, const ::brain_msgs::LanePath_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brain_msgs::LanePath_<ContainerAllocator1> & lhs, const ::brain_msgs::LanePath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brain_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::LanePath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::LanePath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::LanePath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::LanePath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::LanePath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::LanePath_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brain_msgs::LanePath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d66bf89baffff012d456a98e7a25585";
  }

  static const char* value(const ::brain_msgs::LanePath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d66bf89baffff01ULL;
  static const uint64_t static_value2 = 0x2d456a98e7a25585ULL;
};

template<class ContainerAllocator>
struct DataType< ::brain_msgs::LanePath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brain_msgs/LanePath";
  }

  static const char* value(const ::brain_msgs::LanePath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brain_msgs::LanePath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brain_msgs/Relation[] path\n"
"================================================================================\n"
"MSG: brain_msgs/Relation\n"
"int64 id \n"
"uint8 relation\n"
"uint8 unknown=0\n"
"uint8 lane_keeping=1\n"
"uint8 change_left=2\n"
"uint8 change_right=3\n"
"uint8 adjacent_left=4\n"
"uint8 adjacent_right=5\n"
"uint8 conflict=6\n"
"uint8 area=7\n"
;
  }

  static const char* value(const ::brain_msgs::LanePath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brain_msgs::LanePath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LanePath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brain_msgs::LanePath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brain_msgs::LanePath_<ContainerAllocator>& v)
  {
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::brain_msgs::Relation_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRAIN_MSGS_MESSAGE_LANEPATH_H
