// Generated by gencpp from file brain_msgs/Object.msg
// DO NOT EDIT!


#ifndef BRAIN_MSGS_MESSAGE_OBJECT_H
#define BRAIN_MSGS_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <nav_msgs/Odometry.h>
#include <nav_msgs/Odometry.h>
#include <brain_msgs/Size.h>
#include <geometry_msgs/Polygon.h>
#include <brain_msgs/Track.h>
#include <nav_msgs/Odometry.h>
#include <geometry_msgs/Point.h>
#include <brain_msgs/Feature.h>

namespace brain_msgs
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : header()
    , odometry()
    , anchor()
    , size()
    , polygon()
    , track()
    , tracklet()
    , classification(0)
    , level(0)
    , sensor(0)
    , motion_state(0)
    , stop_count(0)
    , intent(0)
    , geometry()
    , feature()  {
    }
  Object_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , odometry(_alloc)
    , anchor(_alloc)
    , size(_alloc)
    , polygon(_alloc)
    , track(_alloc)
    , tracklet(_alloc)
    , classification(0)
    , level(0)
    , sensor(0)
    , motion_state(0)
    , stop_count(0)
    , intent(0)
    , geometry(_alloc)
    , feature(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::nav_msgs::Odometry_<ContainerAllocator>  _odometry_type;
  _odometry_type odometry;

   typedef  ::nav_msgs::Odometry_<ContainerAllocator>  _anchor_type;
  _anchor_type anchor;

   typedef  ::brain_msgs::Size_<ContainerAllocator>  _size_type;
  _size_type size;

   typedef  ::geometry_msgs::Polygon_<ContainerAllocator>  _polygon_type;
  _polygon_type polygon;

   typedef  ::brain_msgs::Track_<ContainerAllocator>  _track_type;
  _track_type track;

   typedef std::vector< ::nav_msgs::Odometry_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::nav_msgs::Odometry_<ContainerAllocator> >> _tracklet_type;
  _tracklet_type tracklet;

   typedef uint8_t _classification_type;
  _classification_type classification;

   typedef uint8_t _level_type;
  _level_type level;

   typedef uint8_t _sensor_type;
  _sensor_type sensor;

   typedef uint8_t _motion_state_type;
  _motion_state_type motion_state;

   typedef uint8_t _stop_count_type;
  _stop_count_type stop_count;

   typedef uint8_t _intent_type;
  _intent_type intent;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _geometry_type;
  _geometry_type geometry;

   typedef  ::brain_msgs::Feature_<ContainerAllocator>  _feature_type;
  _feature_type feature;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(unknown)
  #undef unknown
#endif
#if defined(_WIN32) && defined(unknown_small)
  #undef unknown_small
#endif
#if defined(_WIN32) && defined(unknown_medium)
  #undef unknown_medium
#endif
#if defined(_WIN32) && defined(unknown_big)
  #undef unknown_big
#endif
#if defined(_WIN32) && defined(pedestrian)
  #undef pedestrian
#endif
#if defined(_WIN32) && defined(bike)
  #undef bike
#endif
#if defined(_WIN32) && defined(car)
  #undef car
#endif
#if defined(_WIN32) && defined(truck)
  #undef truck
#endif
#if defined(_WIN32) && defined(motorcycle)
  #undef motorcycle
#endif
#if defined(_WIN32) && defined(other_vehicle)
  #undef other_vehicle
#endif
#if defined(_WIN32) && defined(barrier)
  #undef barrier
#endif
#if defined(_WIN32) && defined(sign)
  #undef sign
#endif
#if defined(_WIN32) && defined(detected)
  #undef detected
#endif
#if defined(_WIN32) && defined(tracked)
  #undef tracked
#endif
#if defined(_WIN32) && defined(fused)
  #undef fused
#endif
#if defined(_WIN32) && defined(predicted)
  #undef predicted
#endif
#if defined(_WIN32) && defined(stop)
  #undef stop
#endif
#if defined(_WIN32) && defined(stationary)
  #undef stationary
#endif
#if defined(_WIN32) && defined(moving)
  #undef moving
#endif
#if defined(_WIN32) && defined(change_lane)
  #undef change_lane
#endif
#if defined(_WIN32) && defined(low_acceleration)
  #undef low_acceleration
#endif
#if defined(_WIN32) && defined(high_acceleration)
  #undef high_acceleration
#endif
#if defined(_WIN32) && defined(low_deceleration)
  #undef low_deceleration
#endif
#if defined(_WIN32) && defined(high_deceleration)
  #undef high_deceleration
#endif

  enum {
    unknown = 0u,
    unknown_small = 1u,
    unknown_medium = 2u,
    unknown_big = 3u,
    pedestrian = 4u,
    bike = 5u,
    car = 6u,
    truck = 7u,
    motorcycle = 8u,
    other_vehicle = 9u,
    barrier = 10u,
    sign = 11u,
    detected = 1u,
    tracked = 2u,
    fused = 3u,
    predicted = 4u,
    stop = 1u,
    stationary = 2u,
    moving = 3u,
    change_lane = 4u,
    low_acceleration = 5u,
    high_acceleration = 6u,
    low_deceleration = 7u,
    high_deceleration = 8u,
  };


  typedef boost::shared_ptr< ::brain_msgs::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brain_msgs::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::brain_msgs::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::brain_msgs::Object > ObjectPtr;
typedef boost::shared_ptr< ::brain_msgs::Object const> ObjectConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brain_msgs::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brain_msgs::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brain_msgs::Object_<ContainerAllocator1> & lhs, const ::brain_msgs::Object_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.odometry == rhs.odometry &&
    lhs.anchor == rhs.anchor &&
    lhs.size == rhs.size &&
    lhs.polygon == rhs.polygon &&
    lhs.track == rhs.track &&
    lhs.tracklet == rhs.tracklet &&
    lhs.classification == rhs.classification &&
    lhs.level == rhs.level &&
    lhs.sensor == rhs.sensor &&
    lhs.motion_state == rhs.motion_state &&
    lhs.stop_count == rhs.stop_count &&
    lhs.intent == rhs.intent &&
    lhs.geometry == rhs.geometry &&
    lhs.feature == rhs.feature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brain_msgs::Object_<ContainerAllocator1> & lhs, const ::brain_msgs::Object_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brain_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::Object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::Object_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brain_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef6a41c47ae91d1345ea7a687bd7aeda";
  }

  static const char* value(const ::brain_msgs::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef6a41c47ae91d13ULL;
  static const uint64_t static_value2 = 0x45ea7a687bd7aedaULL;
};

template<class ContainerAllocator>
struct DataType< ::brain_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brain_msgs/Object";
  }

  static const char* value(const ::brain_msgs::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brain_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Same as derived_object_msgs/Object\n"
"std_msgs/Header header\n"
"\n"
"nav_msgs/Odometry odometry\n"
"nav_msgs/Odometry anchor\n"
"brain_msgs/Size size\n"
"geometry_msgs/Polygon polygon\n"
"brain_msgs/Track track\n"
"nav_msgs/Odometry[] tracklet\n"
"\n"
"uint8 classification\n"
"uint8 unknown=0\n"
"uint8 unknown_small=1\n"
"uint8 unknown_medium=2\n"
"uint8 unknown_big=3\n"
"uint8 pedestrian=4\n"
"uint8 bike=5\n"
"uint8 car=6\n"
"uint8 truck=7\n"
"uint8 motorcycle=8\n"
"uint8 other_vehicle=9\n"
"uint8 barrier=10\n"
"uint8 sign=11\n"
"\n"
"uint8 level\n"
"# uint8 unknown=0\n"
"uint8 detected=1\n"
"uint8 tracked=2\n"
"uint8 fused=3\n"
"uint8 predicted=4\n"
"\n"
"uint8 sensor\n"
"\n"
"uint8 motion_state\n"
"# uint8 unknown=0\n"
"# uint8 stop=1\n"
"# uint8 stationary=2\n"
"# uint8 moving=3\n"
"\n"
"uint8 stop_count\n"
"\n"
"uint8 intent\n"
"# uint8 unknown=0\n"
"uint8 stop=1\n"
"uint8 stationary=2\n"
"uint8 moving=3\n"
"uint8 change_lane=4\n"
"uint8 low_acceleration=5\n"
"uint8 high_acceleration=6\n"
"uint8 low_deceleration=7\n"
"uint8 high_deceleration=8\n"
"\n"
"geometry_msgs/Point[] geometry\n"
"\n"
"Feature feature\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Odometry\n"
"# This represents an estimate of a position and velocity in free space.  \n"
"# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n"
"# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n"
"Header header\n"
"string child_frame_id\n"
"geometry_msgs/PoseWithCovariance pose\n"
"geometry_msgs/TwistWithCovariance twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: brain_msgs/Size\n"
"std_msgs/Header header\n"
"\n"
"float32[] size\n"
"\n"
"# rectangle\n"
"# x: size[0]\n"
"# y: size[1]\n"
"# z: size[2]\n"
"\n"
"uint8 type\n"
"uint8 unknown = 0\n"
"uint8 rectangle = 1 \n"
"uint8 circle = 2\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: brain_msgs/Track\n"
"std_msgs/Header header\n"
"int64 id\n"
"float64[] state\n"
"string[] state_descriptor\n"
"float64[] covariance\n"
"time initial_time\n"
"time update_time\n"
"float64 update_count\n"
"float64[] gate\n"
"uint8 status\n"
"uint8 model\n"
"================================================================================\n"
"MSG: brain_msgs/Feature\n"
"std_msgs/Header header\n"
"\n"
"float64[] features\n"
"uint8 type\n"
"uint8[] dimmension\n"
;
  }

  static const char* value(const ::brain_msgs::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brain_msgs::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.odometry);
      stream.next(m.anchor);
      stream.next(m.size);
      stream.next(m.polygon);
      stream.next(m.track);
      stream.next(m.tracklet);
      stream.next(m.classification);
      stream.next(m.level);
      stream.next(m.sensor);
      stream.next(m.motion_state);
      stream.next(m.stop_count);
      stream.next(m.intent);
      stream.next(m.geometry);
      stream.next(m.feature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brain_msgs::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brain_msgs::Object_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "odometry: ";
    s << std::endl;
    Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "  ", v.odometry);
    s << indent << "anchor: ";
    s << std::endl;
    Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "  ", v.anchor);
    s << indent << "size: ";
    s << std::endl;
    Printer< ::brain_msgs::Size_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
    s << indent << "polygon: ";
    s << std::endl;
    Printer< ::geometry_msgs::Polygon_<ContainerAllocator> >::stream(s, indent + "  ", v.polygon);
    s << indent << "track: ";
    s << std::endl;
    Printer< ::brain_msgs::Track_<ContainerAllocator> >::stream(s, indent + "  ", v.track);
    s << indent << "tracklet[]" << std::endl;
    for (size_t i = 0; i < v.tracklet.size(); ++i)
    {
      s << indent << "  tracklet[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "    ", v.tracklet[i]);
    }
    s << indent << "classification: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.classification);
    s << indent << "level: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.level);
    s << indent << "sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor);
    s << indent << "motion_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motion_state);
    s << indent << "stop_count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop_count);
    s << indent << "intent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.intent);
    s << indent << "geometry[]" << std::endl;
    for (size_t i = 0; i < v.geometry.size(); ++i)
    {
      s << indent << "  geometry[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.geometry[i]);
    }
    s << indent << "feature: ";
    s << std::endl;
    Printer< ::brain_msgs::Feature_<ContainerAllocator> >::stream(s, indent + "  ", v.feature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRAIN_MSGS_MESSAGE_OBJECT_H
