// Generated by gencpp from file brain_msgs/ObjectArray.msg
// DO NOT EDIT!


#ifndef BRAIN_MSGS_MESSAGE_OBJECTARRAY_H
#define BRAIN_MSGS_MESSAGE_OBJECTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <brain_msgs/Object.h>

namespace brain_msgs
{
template <class ContainerAllocator>
struct ObjectArray_
{
  typedef ObjectArray_<ContainerAllocator> Type;

  ObjectArray_()
    : header()
    , objects()  {
    }
  ObjectArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::brain_msgs::Object_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::brain_msgs::Object_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::brain_msgs::ObjectArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brain_msgs::ObjectArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectArray_

typedef ::brain_msgs::ObjectArray_<std::allocator<void> > ObjectArray;

typedef boost::shared_ptr< ::brain_msgs::ObjectArray > ObjectArrayPtr;
typedef boost::shared_ptr< ::brain_msgs::ObjectArray const> ObjectArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brain_msgs::ObjectArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brain_msgs::ObjectArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brain_msgs::ObjectArray_<ContainerAllocator1> & lhs, const ::brain_msgs::ObjectArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brain_msgs::ObjectArray_<ContainerAllocator1> & lhs, const ::brain_msgs::ObjectArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brain_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::ObjectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::ObjectArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::ObjectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::ObjectArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::ObjectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::ObjectArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brain_msgs::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c190b57ef89ed8cd4756d10becaa8e5";
  }

  static const char* value(const ::brain_msgs::ObjectArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c190b57ef89ed8cULL;
  static const uint64_t static_value2 = 0xd4756d10becaa8e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::brain_msgs::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brain_msgs/ObjectArray";
  }

  static const char* value(const ::brain_msgs::ObjectArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brain_msgs::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header      header \n"
"\n"
"brain_msgs/Object[]  objects \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: brain_msgs/Object\n"
"# Same as derived_object_msgs/Object\n"
"std_msgs/Header header\n"
"\n"
"nav_msgs/Odometry odometry\n"
"nav_msgs/Odometry anchor\n"
"brain_msgs/Size size\n"
"geometry_msgs/Polygon polygon\n"
"brain_msgs/Track track\n"
"nav_msgs/Odometry[] tracklet\n"
"\n"
"uint8 classification\n"
"uint8 unknown=0\n"
"uint8 unknown_small=1\n"
"uint8 unknown_medium=2\n"
"uint8 unknown_big=3\n"
"uint8 pedestrian=4\n"
"uint8 bike=5\n"
"uint8 car=6\n"
"uint8 truck=7\n"
"uint8 motorcycle=8\n"
"uint8 other_vehicle=9\n"
"uint8 barrier=10\n"
"uint8 sign=11\n"
"\n"
"uint8 level\n"
"# uint8 unknown=0\n"
"uint8 detected=1\n"
"uint8 tracked=2\n"
"uint8 fused=3\n"
"uint8 predicted=4\n"
"\n"
"uint8 sensor\n"
"\n"
"uint8 motion_state\n"
"# uint8 unknown=0\n"
"# uint8 stop=1\n"
"# uint8 stationary=2\n"
"# uint8 moving=3\n"
"\n"
"uint8 stop_count\n"
"\n"
"uint8 intent\n"
"# uint8 unknown=0\n"
"uint8 stop=1\n"
"uint8 stationary=2\n"
"uint8 moving=3\n"
"uint8 change_lane=4\n"
"uint8 low_acceleration=5\n"
"uint8 high_acceleration=6\n"
"uint8 low_deceleration=7\n"
"uint8 high_deceleration=8\n"
"\n"
"geometry_msgs/Point[] geometry\n"
"\n"
"Feature feature\n"
"================================================================================\n"
"MSG: nav_msgs/Odometry\n"
"# This represents an estimate of a position and velocity in free space.  \n"
"# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n"
"# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n"
"Header header\n"
"string child_frame_id\n"
"geometry_msgs/PoseWithCovariance pose\n"
"geometry_msgs/TwistWithCovariance twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: brain_msgs/Size\n"
"std_msgs/Header header\n"
"\n"
"float32[] size\n"
"\n"
"# rectangle\n"
"# x: size[0]\n"
"# y: size[1]\n"
"# z: size[2]\n"
"\n"
"uint8 type\n"
"uint8 unknown = 0\n"
"uint8 rectangle = 1 \n"
"uint8 circle = 2\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: brain_msgs/Track\n"
"std_msgs/Header header\n"
"int64 id\n"
"float64[] state\n"
"string[] state_descriptor\n"
"float64[] covariance\n"
"time initial_time\n"
"time update_time\n"
"float64 update_count\n"
"float64[] gate\n"
"uint8 status\n"
"uint8 model\n"
"================================================================================\n"
"MSG: brain_msgs/Feature\n"
"std_msgs/Header header\n"
"\n"
"float64[] features\n"
"uint8 type\n"
"uint8[] dimmension\n"
;
  }

  static const char* value(const ::brain_msgs::ObjectArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brain_msgs::ObjectArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brain_msgs::ObjectArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brain_msgs::ObjectArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::brain_msgs::Object_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRAIN_MSGS_MESSAGE_OBJECTARRAY_H
