// Generated by gencpp from file brain_msgs/PathNode.msg
// DO NOT EDIT!


#ifndef BRAIN_MSGS_MESSAGE_PATHNODE_H
#define BRAIN_MSGS_MESSAGE_PATHNODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace brain_msgs
{
template <class ContainerAllocator>
struct PathNode_
{
  typedef PathNode_<ContainerAllocator> Type;

  PathNode_()
    : pose()
    , dir(0)  {
    }
  PathNode_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , dir(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef int8_t _dir_type;
  _dir_type dir;





  typedef boost::shared_ptr< ::brain_msgs::PathNode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brain_msgs::PathNode_<ContainerAllocator> const> ConstPtr;

}; // struct PathNode_

typedef ::brain_msgs::PathNode_<std::allocator<void> > PathNode;

typedef boost::shared_ptr< ::brain_msgs::PathNode > PathNodePtr;
typedef boost::shared_ptr< ::brain_msgs::PathNode const> PathNodeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brain_msgs::PathNode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brain_msgs::PathNode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brain_msgs::PathNode_<ContainerAllocator1> & lhs, const ::brain_msgs::PathNode_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.dir == rhs.dir;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brain_msgs::PathNode_<ContainerAllocator1> & lhs, const ::brain_msgs::PathNode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brain_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::PathNode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::PathNode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::PathNode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::PathNode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::PathNode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::PathNode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brain_msgs::PathNode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "185f53685cbc3ef3ae21f3995824edc1";
  }

  static const char* value(const ::brain_msgs::PathNode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x185f53685cbc3ef3ULL;
  static const uint64_t static_value2 = 0xae21f3995824edc1ULL;
};

template<class ContainerAllocator>
struct DataType< ::brain_msgs::PathNode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brain_msgs/PathNode";
  }

  static const char* value(const ::brain_msgs::PathNode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brain_msgs::PathNode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"int8               dir\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::brain_msgs::PathNode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brain_msgs::PathNode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.dir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathNode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brain_msgs::PathNode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brain_msgs::PathNode_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "dir: ";
    Printer<int8_t>::stream(s, indent + "  ", v.dir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRAIN_MSGS_MESSAGE_PATHNODE_H
