// Generated by gencpp from file brain_msgs/Size.msg
// DO NOT EDIT!


#ifndef BRAIN_MSGS_MESSAGE_SIZE_H
#define BRAIN_MSGS_MESSAGE_SIZE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace brain_msgs
{
template <class ContainerAllocator>
struct Size_
{
  typedef Size_<ContainerAllocator> Type;

  Size_()
    : header()
    , size()
    , type(0)  {
    }
  Size_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , size(_alloc)
    , type(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _size_type;
  _size_type size;

   typedef uint8_t _type_type;
  _type_type type;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(unknown)
  #undef unknown
#endif
#if defined(_WIN32) && defined(rectangle)
  #undef rectangle
#endif
#if defined(_WIN32) && defined(circle)
  #undef circle
#endif

  enum {
    unknown = 0u,
    rectangle = 1u,
    circle = 2u,
  };


  typedef boost::shared_ptr< ::brain_msgs::Size_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brain_msgs::Size_<ContainerAllocator> const> ConstPtr;

}; // struct Size_

typedef ::brain_msgs::Size_<std::allocator<void> > Size;

typedef boost::shared_ptr< ::brain_msgs::Size > SizePtr;
typedef boost::shared_ptr< ::brain_msgs::Size const> SizeConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brain_msgs::Size_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brain_msgs::Size_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brain_msgs::Size_<ContainerAllocator1> & lhs, const ::brain_msgs::Size_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.size == rhs.size &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brain_msgs::Size_<ContainerAllocator1> & lhs, const ::brain_msgs::Size_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brain_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::Size_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::Size_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::Size_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::Size_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::Size_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::Size_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brain_msgs::Size_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d3d33706a038d2e61a317a5a82178df";
  }

  static const char* value(const ::brain_msgs::Size_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d3d33706a038d2eULL;
  static const uint64_t static_value2 = 0x61a317a5a82178dfULL;
};

template<class ContainerAllocator>
struct DataType< ::brain_msgs::Size_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brain_msgs/Size";
  }

  static const char* value(const ::brain_msgs::Size_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brain_msgs::Size_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float32[] size\n"
"\n"
"# rectangle\n"
"# x: size[0]\n"
"# y: size[1]\n"
"# z: size[2]\n"
"\n"
"uint8 type\n"
"uint8 unknown = 0\n"
"uint8 rectangle = 1 \n"
"uint8 circle = 2\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::brain_msgs::Size_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brain_msgs::Size_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.size);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Size_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brain_msgs::Size_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brain_msgs::Size_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "size[]" << std::endl;
    for (size_t i = 0; i < v.size.size(); ++i)
    {
      s << indent << "  size[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.size[i]);
    }
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRAIN_MSGS_MESSAGE_SIZE_H
