// Generated by gencpp from file brain_msgs/TrafficLight.msg
// DO NOT EDIT!


#ifndef BRAIN_MSGS_MESSAGE_TRAFFICLIGHT_H
#define BRAIN_MSGS_MESSAGE_TRAFFICLIGHT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseWithCovariance.h>

namespace brain_msgs
{
template <class ContainerAllocator>
struct TrafficLight_
{
  typedef TrafficLight_<ContainerAllocator> Type;

  TrafficLight_()
    : header()
    , state(0)
    , state_probability(0.0)
    , type(0)
    , is_its(false)
    , intersection_id(0)
    , group_id(0)
    , end_time(0.0)
    , level(0)
    , track_id(0)
    , pose()  {
    }
  TrafficLight_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , state_probability(0.0)
    , type(0)
    , is_its(false)
    , intersection_id(0)
    , group_id(0)
    , end_time(0.0)
    , level(0)
    , track_id(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _state_type;
  _state_type state;

   typedef float _state_probability_type;
  _state_probability_type state_probability;

   typedef uint8_t _type_type;
  _type_type type;

   typedef uint8_t _is_its_type;
  _is_its_type is_its;

   typedef int64_t _intersection_id_type;
  _intersection_id_type intersection_id;

   typedef int64_t _group_id_type;
  _group_id_type group_id;

   typedef float _end_time_type;
  _end_time_type end_time;

   typedef uint8_t _level_type;
  _level_type level;

   typedef int64_t _track_id_type;
  _track_id_type track_id;

   typedef  ::geometry_msgs::PoseWithCovariance_<ContainerAllocator>  _pose_type;
  _pose_type pose;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(unknown)
  #undef unknown
#endif
#if defined(_WIN32) && defined(red)
  #undef red
#endif
#if defined(_WIN32) && defined(yellow)
  #undef yellow
#endif
#if defined(_WIN32) && defined(green)
  #undef green
#endif
#if defined(_WIN32) && defined(green_left)
  #undef green_left
#endif
#if defined(_WIN32) && defined(red_left)
  #undef red_left
#endif
#if defined(_WIN32) && defined(str)
  #undef str
#endif
#if defined(_WIN32) && defined(left)
  #undef left
#endif
#if defined(_WIN32) && defined(ped)
  #undef ped
#endif
#if defined(_WIN32) && defined(uturn)
  #undef uturn
#endif
#if defined(_WIN32) && defined(detected)
  #undef detected
#endif
#if defined(_WIN32) && defined(tracked)
  #undef tracked
#endif
#if defined(_WIN32) && defined(fused)
  #undef fused
#endif
#if defined(_WIN32) && defined(predicted)
  #undef predicted
#endif

  enum {
    unknown = 0u,
    red = 1u,
    yellow = 2u,
    green = 3u,
    green_left = 4u,
    red_left = 5u,
    str = 1u,
    left = 2u,
    ped = 3u,
    uturn = 4u,
    detected = 1u,
    tracked = 2u,
    fused = 3u,
    predicted = 4u,
  };


  typedef boost::shared_ptr< ::brain_msgs::TrafficLight_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brain_msgs::TrafficLight_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficLight_

typedef ::brain_msgs::TrafficLight_<std::allocator<void> > TrafficLight;

typedef boost::shared_ptr< ::brain_msgs::TrafficLight > TrafficLightPtr;
typedef boost::shared_ptr< ::brain_msgs::TrafficLight const> TrafficLightConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brain_msgs::TrafficLight_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brain_msgs::TrafficLight_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brain_msgs::TrafficLight_<ContainerAllocator1> & lhs, const ::brain_msgs::TrafficLight_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state &&
    lhs.state_probability == rhs.state_probability &&
    lhs.type == rhs.type &&
    lhs.is_its == rhs.is_its &&
    lhs.intersection_id == rhs.intersection_id &&
    lhs.group_id == rhs.group_id &&
    lhs.end_time == rhs.end_time &&
    lhs.level == rhs.level &&
    lhs.track_id == rhs.track_id &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brain_msgs::TrafficLight_<ContainerAllocator1> & lhs, const ::brain_msgs::TrafficLight_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brain_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::TrafficLight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::TrafficLight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::TrafficLight_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::TrafficLight_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::TrafficLight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::TrafficLight_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brain_msgs::TrafficLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49f0776ab5b2d8920fe13d11d3c5ced6";
  }

  static const char* value(const ::brain_msgs::TrafficLight_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49f0776ab5b2d892ULL;
  static const uint64_t static_value2 = 0x0fe13d11d3c5ced6ULL;
};

template<class ContainerAllocator>
struct DataType< ::brain_msgs::TrafficLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brain_msgs/TrafficLight";
  }

  static const char* value(const ::brain_msgs::TrafficLight_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brain_msgs::TrafficLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message defines meta information for a traffic light status\n"
"std_msgs/Header header\n"
"\n"
"# The result as provided by the tlr nodes\n"
"# Red and Yellow states are both treated as STOP\n"
"uint8 state\n"
"uint8 unknown    = 0\n"
"uint8 red        = 1\n"
"uint8 yellow     = 2\n"
"uint8 green      = 3\n"
"uint8 green_left = 4\n"
"uint8 red_left   = 5\n"
"\n"
"# Probability of state [0,1]\n"
"# if is_its is true, it is set to be 1\n"
"float32 state_probability\n"
"\n"
"# type\n"
"uint8 type\n"
"# uint8 UNKNOWN = 0\n"
"uint8 str       = 1\n"
"uint8 left      = 2\n"
"uint8 ped       = 3\n"
"uint8 uturn     = 4\n"
"\n"
"\n"
"## --------------------\n"
"## ITS ONLY INFORMATION\n"
"# true when it comes from ITS\n"
"bool is_its\n"
"\n"
"# available when is_its is true\n"
"int64 intersection_id\n"
"\n"
"# ID is avalialbe, if is_its is true\n"
"int64 group_id\n"
"\n"
"# remaining time to be changed\n"
"float32 end_time # [sec]\n"
"## --------------------\n"
"\n"
"\n"
"## --------------------\n"
"## INFORMATION FROM DETECTION AND TRACKING\n"
"# Perception procssing level\n"
"uint8 level\n"
"uint8 detected=1\n"
"uint8 tracked=2\n"
"uint8 fused=3\n"
"uint8 predicted=4\n"
"\n"
"# ID is avaliable, if perception level is tracking\n"
"int64 track_id\n"
"\n"
"# Positional information of the traffic light information\n"
"geometry_msgs/PoseWithCovariance pose\n"
"## --------------------\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::brain_msgs::TrafficLight_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brain_msgs::TrafficLight_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.state_probability);
      stream.next(m.type);
      stream.next(m.is_its);
      stream.next(m.intersection_id);
      stream.next(m.group_id);
      stream.next(m.end_time);
      stream.next(m.level);
      stream.next(m.track_id);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficLight_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brain_msgs::TrafficLight_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brain_msgs::TrafficLight_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "state_probability: ";
    Printer<float>::stream(s, indent + "  ", v.state_probability);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "is_its: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_its);
    s << indent << "intersection_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.intersection_id);
    s << indent << "group_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.group_id);
    s << indent << "end_time: ";
    Printer<float>::stream(s, indent + "  ", v.end_time);
    s << indent << "level: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.level);
    s << indent << "track_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.track_id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRAIN_MSGS_MESSAGE_TRAFFICLIGHT_H
