// Generated by gencpp from file brain_msgs/TurnSignal.msg
// DO NOT EDIT!


#ifndef BRAIN_MSGS_MESSAGE_TURNSIGNAL_H
#define BRAIN_MSGS_MESSAGE_TURNSIGNAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace brain_msgs
{
template <class ContainerAllocator>
struct TurnSignal_
{
  typedef TurnSignal_<ContainerAllocator> Type;

  TurnSignal_()
    : signal(0)  {
    }
  TurnSignal_(const ContainerAllocator& _alloc)
    : signal(0)  {
  (void)_alloc;
    }



   typedef uint8_t _signal_type;
  _signal_type signal;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(off)
  #undef off
#endif
#if defined(_WIN32) && defined(left)
  #undef left
#endif
#if defined(_WIN32) && defined(right)
  #undef right
#endif
#if defined(_WIN32) && defined(hazard)
  #undef hazard
#endif

  enum {
    off = 0u,
    left = 1u,
    right = 2u,
    hazard = 3u,
  };


  typedef boost::shared_ptr< ::brain_msgs::TurnSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brain_msgs::TurnSignal_<ContainerAllocator> const> ConstPtr;

}; // struct TurnSignal_

typedef ::brain_msgs::TurnSignal_<std::allocator<void> > TurnSignal;

typedef boost::shared_ptr< ::brain_msgs::TurnSignal > TurnSignalPtr;
typedef boost::shared_ptr< ::brain_msgs::TurnSignal const> TurnSignalConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brain_msgs::TurnSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brain_msgs::TurnSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brain_msgs::TurnSignal_<ContainerAllocator1> & lhs, const ::brain_msgs::TurnSignal_<ContainerAllocator2> & rhs)
{
  return lhs.signal == rhs.signal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brain_msgs::TurnSignal_<ContainerAllocator1> & lhs, const ::brain_msgs::TurnSignal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brain_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::TurnSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::TurnSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::TurnSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::TurnSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::TurnSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::TurnSignal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brain_msgs::TurnSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0300e4766b90b3c18f0403ee3ce368ce";
  }

  static const char* value(const ::brain_msgs::TurnSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0300e4766b90b3c1ULL;
  static const uint64_t static_value2 = 0x8f0403ee3ce368ceULL;
};

template<class ContainerAllocator>
struct DataType< ::brain_msgs::TurnSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brain_msgs/TurnSignal";
  }

  static const char* value(const ::brain_msgs::TurnSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brain_msgs::TurnSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 signal\n"
"uint8 off=0\n"
"uint8 left=1\n"
"uint8 right=2\n"
"uint8 hazard=3\n"
;
  }

  static const char* value(const ::brain_msgs::TurnSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brain_msgs::TurnSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurnSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brain_msgs::TurnSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brain_msgs::TurnSignal_<ContainerAllocator>& v)
  {
    s << indent << "signal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRAIN_MSGS_MESSAGE_TURNSIGNAL_H
