// Generated by gencpp from file brain_msgs/UserRequest.msg
// DO NOT EDIT!


#ifndef BRAIN_MSGS_MESSAGE_USERREQUEST_H
#define BRAIN_MSGS_MESSAGE_USERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace brain_msgs
{
template <class ContainerAllocator>
struct UserRequest_
{
  typedef UserRequest_<ContainerAllocator> Type;

  UserRequest_()
    : header()
    , request(0)  {
    }
  UserRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , request(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _request_type;
  _request_type request;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(no_action)
  #undef no_action
#endif
#if defined(_WIN32) && defined(destination)
  #undef destination
#endif
#if defined(_WIN32) && defined(start)
  #undef start
#endif
#if defined(_WIN32) && defined(tele_operation)
  #undef tele_operation
#endif
#if defined(_WIN32) && defined(complete)
  #undef complete
#endif
#if defined(_WIN32) && defined(pause)
  #undef pause
#endif

  enum {
    no_action = 0u,
    destination = 1u,
    start = 2u,
    tele_operation = 3u,
    complete = 4u,
    pause = 5u,
  };


  typedef boost::shared_ptr< ::brain_msgs::UserRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brain_msgs::UserRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UserRequest_

typedef ::brain_msgs::UserRequest_<std::allocator<void> > UserRequest;

typedef boost::shared_ptr< ::brain_msgs::UserRequest > UserRequestPtr;
typedef boost::shared_ptr< ::brain_msgs::UserRequest const> UserRequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brain_msgs::UserRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brain_msgs::UserRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brain_msgs::UserRequest_<ContainerAllocator1> & lhs, const ::brain_msgs::UserRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brain_msgs::UserRequest_<ContainerAllocator1> & lhs, const ::brain_msgs::UserRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brain_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::UserRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::UserRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::UserRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::UserRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::UserRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::UserRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brain_msgs::UserRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "204e0dead2d18d7d0c441c2f4f3ff636";
  }

  static const char* value(const ::brain_msgs::UserRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x204e0dead2d18d7dULL;
  static const uint64_t static_value2 = 0x0c441c2f4f3ff636ULL;
};

template<class ContainerAllocator>
struct DataType< ::brain_msgs::UserRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brain_msgs/UserRequest";
  }

  static const char* value(const ::brain_msgs::UserRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brain_msgs::UserRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header    header \n"
"\n"
"uint8              request\n"
"uint8              no_action=0\n"
"uint8              destination=1\n"
"uint8              start=2\n"
"uint8              tele_operation=3\n"
"uint8              complete=4\n"
"uint8              pause=5\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::brain_msgs::UserRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brain_msgs::UserRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UserRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brain_msgs::UserRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brain_msgs::UserRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRAIN_MSGS_MESSAGE_USERREQUEST_H
