// Generated by gencpp from file brain_msgs/Waypoints.msg
// DO NOT EDIT!


#ifndef BRAIN_MSGS_MESSAGE_WAYPOINTS_H
#define BRAIN_MSGS_MESSAGE_WAYPOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <brain_msgs/Waypoint.h>

namespace brain_msgs
{
template <class ContainerAllocator>
struct Waypoints_
{
  typedef Waypoints_<ContainerAllocator> Type;

  Waypoints_()
    : header()
    , num_points(0)
    , points()  {
    }
  Waypoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , num_points(0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _num_points_type;
  _num_points_type num_points;

   typedef std::vector< ::brain_msgs::Waypoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::brain_msgs::Waypoint_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::brain_msgs::Waypoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brain_msgs::Waypoints_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoints_

typedef ::brain_msgs::Waypoints_<std::allocator<void> > Waypoints;

typedef boost::shared_ptr< ::brain_msgs::Waypoints > WaypointsPtr;
typedef boost::shared_ptr< ::brain_msgs::Waypoints const> WaypointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brain_msgs::Waypoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brain_msgs::Waypoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brain_msgs::Waypoints_<ContainerAllocator1> & lhs, const ::brain_msgs::Waypoints_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.num_points == rhs.num_points &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brain_msgs::Waypoints_<ContainerAllocator1> & lhs, const ::brain_msgs::Waypoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brain_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::Waypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brain_msgs::Waypoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::Waypoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brain_msgs::Waypoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::Waypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brain_msgs::Waypoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brain_msgs::Waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4d51bc282097ce3ba98c8e265803dee";
  }

  static const char* value(const ::brain_msgs::Waypoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4d51bc282097ce3ULL;
  static const uint64_t static_value2 = 0xba98c8e265803deeULL;
};

template<class ContainerAllocator>
struct DataType< ::brain_msgs::Waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brain_msgs/Waypoints";
  }

  static const char* value(const ::brain_msgs::Waypoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brain_msgs::Waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header         header \n"
"uint16                  num_points\n"
"brain_msgs/Waypoint[]   points\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: brain_msgs/Waypoint\n"
"std_msgs/Header     header \n"
"brain_msgs/Wgs84    point\n"
"================================================================================\n"
"MSG: brain_msgs/Wgs84\n"
"float64 latitude\n"
"float64 longitude\n"
"float32 height\n"
"float32 heading\n"
"uint8 status\n"
"uint8 valid=0\n"
"uint8 invalid=1\n"
;
  }

  static const char* value(const ::brain_msgs::Waypoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brain_msgs::Waypoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.num_points);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brain_msgs::Waypoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brain_msgs::Waypoints_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "num_points: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.num_points);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::brain_msgs::Waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRAIN_MSGS_MESSAGE_WAYPOINTS_H
